# Application Configuration
spring.application.name=minikube-sample-app

# Server Configuration
server.port=8080

# # Environment Configuration
# ENV_DEPLOYED=demo

# Custom Properties (based on PropertiesConfig usage)
app.data.name=Sample Application
app.data.test=Test Value
